# Generated by Django 5.2.1 on 2025-06-28 11:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_sms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_date',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_sender',
        ),
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date sent'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='web_sms.account'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='web_sms.account'),
        ),
    ]
