# Generated by Django 5.2.1 on 2025-06-28 11:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_sms', '0002_rename_message_text_message_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date sent'),
        ),
    ]
