# Generated by Django 5.2.1 on 2025-07-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_sms', '0003_alter_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='secret_answer',
            field=models.CharField(default='default answer', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='secret_question',
            field=models.CharField(default='default question', max_length=100),
            preserve_default=False,
        ),
    ]
