# Generated by Django 5.2.1 on 2025-07-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_sms', '0004_account_secret_answer_account_secret_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
